[project]
name = "learnin-litestar"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "litestar[sqlalchemy,standard]>=2.15.2",
    "sqlalchemy>=2.0.40",
]
